registry: ""
version: "latest"

namespace: ""

repoUrl: ""
repoRef: "main"

storage:
  size: 50Gi

minio:
  storage: 20Gi
  rootUser: minio
  rootPassword: minio123
  bucket: mlpipeline

dataGeneration:
  name: agent-mesh-for-sw-modernization-data-generation
  resources:
    requests:
      cpu: "2"
      memory: 8Gi
    limits:
      cpu: "4"
      memory: 16Gi

dataIndexing:
  name: agent-mesh-for-sw-modernization-data-indexing
  resources:
    requests:
      cpu: "2"
      memory: 8Gi
    limits:
      cpu: "4"
      memory: 16Gi
